---
  - hosts: loadbalancer
    become: true
    tasks:
      - name: Install Nginx
        yum: name={{item}} state=present
        with_items: 
          - nginx
      - name: Start Nginx Server
        service: name=nginx state=started