---
- name: Install Nginx
  yum: name={{item}} state=present
  with_items: 
    - nginx

- name: Configure Nginx Sites
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: 0755
  notify:
    - Restart Nginx

- name: Create an empty sites-enabled directory
  file: path=/etc/nginx/sites-available state={{item}}
  with_items:
    - absent
    - directory

- name: Create configs
  template:
    src: sites.conf.j2
    dest: /etc/nginx/sites-enabled/{{item.key}}.conf
    mode: 0755
  with_dict: '{{sites}}'
  notify:
    - Restart Nginx

- name: Start Nginx Server
  service: name=nginx state=started